version: "2.3"

services:
  dnf-server:
    image: xanderye/dnf-server:centos7
    environment:
      - TZ=Asia/Shanghai
      # 关闭自动获取
      - AUTO_MYSQL_IP=false
      # mysql的IP地址
      - MYSQL_IP=192.168.1.2
      # mysql的IP端口
      - MYSQL_PORT=3306
      # game账户密码
      - GAME_PASSWORD=uu5!^%jg
      # 自动获取公网ip
      - AUTO_PUBLIC_IP=false
      # 这里填写你的IP地址
      - PUBLIC_IP=127.0.0.1
      - GM_ACCOUNT=gm_user
      - GM_PASSWORD=123456
      - GM_CONNECT_KEY=763WXRBW3PFTC3IXPFWH
      - GM_LANDER_VERSION=20180307
    shm_size: 8g
    memswap_limit: -1
    mem_limit: 1g
    # windows下生效
    cpu_count: 1
    # 占用1个cpu
    cpus: 1.0
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 7600:7600/tcp       # DnfGateServe 网关
      - 881:881/tcp         # DnfGateServe 网关
      - 20303:20303/tcp     # df_dbmw_r
      - 20303:20303/udp     # df_dbmw_r
      - 20403:20403/tcp     # df_dbmw_r
      - 20403:20403/udp     # df_dbmw_r
      - 40403:40403/tcp     # df_manager_r
      - 40403:40403/udp     # df_manager_r
      - 7000:7000/tcp       # df_bridge_r
      - 7000:7000/udp       # df_bridge_r
      - 7001:7001/tcp       # df_channel_r
      - 7001:7001/udp       # df_channel_r
      - 7200:7200/tcp       # df_relay_r
      - 7200:7200/udp       # df_relay_r
      - 10011:10011/tcp     # df_game_r
      - 31100:31100/tcp     # df_community
      - 30303:30303/tcp     # df_monitor_r
      - 30303:30303/udp     # df_monitor_r
      - 30403:30403/tcp     # df_guild_r
      - 30403:30403/udp     # df_guild_r
      - 10052:10052/tcp     # df_game_r
      - 20011:20011/tcp     # df_game_r
      - 20203:20203/tcp     # df_dbmw_r
      - 20203:20203/udp     # df_dbmw_r
      - 30703:30703/udp     # df_coserver_r
      - 11011:11011/udp     # df_game_r
      - 2311-2313:2311-2313/udp   # df_stun_r
      - 30503:30503/udp     # df_statics_r
      - 11052:11052/udp     # df_game_r
    volumes:
      - ./data:/data
      - ./log:/home/neople/game/log
    container_name: dnfserver